apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: tekton-catalog-automated-testing-event-listener
spec:
  triggers:
    - name: open-pr-integration-test
      interceptors:
      - ref:
          name: "github"
        params:
        - name: "eventTypes"
          value: ["pull_request"]
      - ref:
          name: "cel"
        params:
        - name: "filter"
          value: "body.action in ['opened', 'synchronize', 'reopened']"
      template:
        ref: catalog-integration-test-template
      bindings:
      - name: repo-full-name
        value: $(body.repository.full_name)
      - name: git-sha
        value: $(body.pull_request.head.sha)
      - name: checkrun-name
        value: catalog-integration-test
      - name: pullRequestNumber
        value: $(body.number)
      - name: pullRequestBaseRef
        value: $(body.pull_request.base.ref)
      - name: gitRepository
        value: $(body.repository.html_url)
      - name: e2e-env
        value: ./test/e2e-kind.env
    - name: pull-integration-test
      interceptors:
      - ref:  # This interceptor filters the event types
          name: "github"
        params:
        - name: "eventTypes"
          value: ["issue_comment"]
      - ref:  # This interceptor filters the comment prefix
          name: "cel"
        params:
        - name: "filter"
          value: "body.comment.body == '/test pull-tekton-integration-test'"
        - name: "overlays"
          value:
          - key: add_pr_body.pull_request_url
            expression: "body.issue.pull_request.url"
      - webhook:
          objectRef:
            kind: Service
            name: add-pr-body
            apiVersion: v1
      template:
        ref: catalog-integration-test-template
      bindings:
      - name: repo-full-name
        value: $(body.repository.full_name)
      - name: git-sha
        value: $(body.extensions.add_pr_body.pull_request_body.head.sha)
      - name: checkrun-name
        value: catalog-integration-test
      - name: pullRequestNumber
        value: $(body.issue.number)
      - name: pullRequestBaseRef
        value: $(body.extensions.add_pr_body.pull_request_body.base.ref)
      - name: gitRepository
        value: $(body.repository.html_url)
      - name: e2e-env
        value: ./test/e2e-kind.env
    - name: open-pr-build-test
      interceptors:
      - ref:
          name: "github"
        params:
        - name: "eventTypes"
          value: ["pull_request"]
      - ref:
          name: "cel"
        params:
        - name: "filter"
          value: "body.action in ['opened', 'synchronize', 'reopened']"
      template:
        ref: catalog-build-test-template
      bindings:
      - name: repo-full-name
        value: $(body.repository.full_name)
      - name: git-sha
        value: $(body.pull_request.head.sha)
      - name: check-run-name
        value: catalog-build-test
      - name: gitCloneDepth
        value: $(body.pull_request.commits)
      - name: pullRequestUrl
        value: $(body.pull_request.html_url)
      - name: pullRequestNumber
        value: $(body.number)
      - name: pullRequestBaseRef
        value: $(body.pull_request.base.ref)
      - name: gitRepository
        value: $(body.repository.html_url)
    - name: pull-build-test
      interceptors:
      - ref:
          name: "github"
        params:
        - name: "eventTypes"
          value: ["issue_comment"]
      - ref:
          name: "cel"
        params:
        - name: "filter"
          value: "body.comment.body == '/test pull-tekton-build-test'"
        - name: "overlays"
          value:
          - key: add_pr_body.pull_request_url
            expression: "body.issue.pull_request.url"
      - webhook:
          objectRef:
            kind: Service
            name: add-pr-body
            apiVersion: v1
      template:
        ref: catalog-build-test-template
      bindings:
      - name: repo-full-name
        value: $(body.repository.full_name)
      - name: git-sha
        value: $(body.extensions.add_pr_body.pull_request_body.head.sha)
      - name: check-run-name
        value: catalog-build-test
      - name: gitCloneDepth
        value: $(body.extensions.add_pr_body.pull_request_body.commits)
      - name: pullRequestUrl
        value: $(body.issue.pull_request.html_url)
      - name: pullRequestNumber
        value: $(body.issue.number)
      - name: pullRequestBaseRef
        value: $(body.extensions.add_pr_body.pull_request_body.base.ref)
      - name: gitRepository
        value: $(body.repository.html_url)
  resources:
    kubernetesResource:
      serviceType: LoadBalancer
      spec:
        template:
          spec:
            serviceAccountName: tekton-catalog-automated-testing-sa