apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: send-basic-comment-github-run
spec:
  pipelineRef:
    name: send-basic-comment-github
  params:
  - name: REQUEST_URL
    value: https://github.com/QuanZhang-William/ah-test-catalog-git-versioning/pull/1
  - name: COMMENT_OR_FILE
    value: This is a comment from Tekton CI