apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: send-github-check-template
spec:
  params:
  - name: repo-full-name
  - name: git-sha
  - name: checkrun-name
    default: el-tekton-ci
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: create-basic-check-github-run
    spec:
      pipelineRef:
        name: create-basic-check-github
      params: 
      - name: repo-full-name
        value: $(tt.params.repo-full-name)
      - name: git-sha
        value: $(tt.params.git-sha)
      - name: check-run-name
        value: $(tt.params.checkrun-name)
      workspaces:
      - name: github-app-secret
        secret:
          secretName: github-app-secret