apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kind-e2e
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Kubernetes
    tekton.dev/displayName: "kind"
    tekton.dev/tags: "kind"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    Sets up and executes commands in KinD (Kubernetes in Docker) environment.
    See https://kind.sigs.k8s.io for more details.
  params:
    - name: arguments
      type: array
      description: args to pass to the kind script
  workspaces:
    - name: source
  steps:
    - name: make-artifacts-folder
      image: alpine:3.15.3
      env:
        - name: ARTIFACTS_FOLDER
          value: "$(workspaces.source.path)/artifacts"
      script: |
        #!/bin/sh
        set -ex
        mkdir -p "$ARTIFACTS_FOLDER"
        echo "Created folder $ARTIFACTS_FOLDER"
    - image: gcr.io/tekton-releases/dogfooding/kind-e2e:latest
      imagePullPolicy: Always
      workingDir: $(workspaces.source.path)
      name: kind
      volumeMounts:
        - mountPath: /var/run/
          name: dind-socket
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      args: ["$(params.arguments[*])"]
  sidecars:
    - image: docker:20.10.11-dind
      name: dind-sidecar
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
        - mountPath: /var/run/
          name: dind-socket
      readinessProbe:
        exec:
          command:
          - docker
          - ps
        initialDelaySeconds: 5
        periodSeconds: 5
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: dind-socket
      emptyDir: {}
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory